### ISSUE TITLE
Would like to add multiple [ConsoleCommand] attributes to a single function.

### ISSUE THREAD

**Issue by Monsoonexe** [Elringus/UnityConsole#1]
Feature request:

Sometimes I want multiple commands to trigger the same function. For example: removeItems and removeAllItems.  This can be accomplished by making multiple functions with different names, but it would be convenient to just add the attribute multiple times.

**Comment by elringus** [comment]
I don't think this is a good idea. As I see it, mapping multiple commands to a single function just brings confusion. Feel free to provide valid use cases if I'm missing something.

**Comment by Monsoonexe** [comment]
The concept is called "aliasing", and it is a  common tool in console
programs. For example, powershell's commandlet Get-Process has an alias ps.
Sometimes it's convenient to have a shorter alias for a long command name.

**Comment by elringus** [comment]
It's already possible to use an alias for the mapped method, in which case it should be used instead of the full method name.
